FROM python:3.7.3-stretch

## Complete Step 1:
# Create a Working Directory

## Complete Step 2:
# Copy source code to working directory

## Complete Step 3:
# Install packages from requirements.txt
# hadolint ignore=DL3013

## Complete Step 4:
# Expose port 80

## Complete Step 5:
# Run app.py at container launch


# FROM node:12.16.3

# WORDDIR /code

# ENV PORT 80

# COPY package.json /code/package

# RUN npm install

# COPY ./code

# CMD ["node", "src/server.js"]